baseURL = 'https://jdy4k.github.io/personal-site/'
languageCode = 'en-us'
title = 'Jack Hosler'
theme = 'hugo-coder'

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Jack Hosler"
description = "Jack Hosler's personal website"
keywords = "blog,bioinformatics,personal"
info = ["Bioinformatics"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2025
rtl = false
colorScheme = "light"
hideColorSchemeToggle = true
maxSeeAlsoItems = 5
customCSS = []
customSCSS = ["scss/resume.scss"]
customJS = []
customRemoteJS = []
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/jdy4k/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/jackhosler/"

[[params.social]]
name = "Email"
icon = "fa fa-envelope fa-2x"
weight = 4
url = "mailto:contact@jackhosler.com"

[[menu.main]]
name = "RESUME"
weight = 1
url = "resume/"
